spring.application.name=charging_station_management
server.port=8080

# ===============================
# Datasource (PostgreSQL - Docker)
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://postgres:5432/charging_station_db}
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:admin}

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
app.jwtSecret=${JWT_SECRET:myVerySecretKeyThatIsAtLeast32CharactersLongForSecurityPurposes}
app.jwtExpirationMs=86400000

# Upload dir trong container
application.upload-dir=/app/uploads

# ===============================
# Mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# CORS
# ===============================
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
